# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'N2FLIX' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for N2FLIX

  target 'N2FLIXTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'N2FLIXUITests' do
    # Pods for testing
  end

end
